### ISSUE TITLE
Definitions for globally scoped objects such as disk, node, cluster

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/specifications#101]
Tendrl needs to understand and support some specific objects such as clusters, hosts, networks, disks, partitions etc. While these are tackled via the inventory in the node agent, they need to be made available in a definition file that's shipped by default with Tendrl. These objects need to be in the global namespace and should have attributes, atoms and flows that enable basic state monitoring and management.

**Comment by GowthamShanmugam** [comment]
@brainfunked for node inventory we already creating objects in tendrl definition file.
