### ISSUE TITLE
Object listing in tendrl should support filtering and sorting at multiple levels

### ISSUE THREAD

**Issue by shtripat** [Tendrl/specifications#103]
Currently the `list` attribute under each object definition in definitions files just mentions a URL which can be used to get the full list of objects of the said type from tendrl central store.

It should extensible to a level where we can can decide the supported sorting on multiple levels from the attribute's list of the object based on data types.

Also filtering based on different attributes and values should be supported. This should not limit to a specific value for an attribute, rather based on data type we should be able to decide the range and set of values as filter as well.

**Comment by r0h4n** [comment]
Is this for the API?

**Comment by shtripat** [comment]
@r0h4n its is for the API, but could be useful if some CLI based tool as well uses the data and wants data more precise (filtered or sorted).
