### ISSUE TITLE
Repository name changes

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/specifications#12]
Repository names need to be updated to follow lowercase, hyphenated convention. The specification needs to point out affected repositories and any code and packaging changes required.

**Comment by mbukatov** [comment]
I guess you don't include a name of the github group (`Tendrl`) in this, but I would rather ask.

**Comment by brainfunked** [comment]
@mbukatov Yeah, we don't need to. However, I'd request @nthomas-redhat to start the spec with the initial details about the changes so that @mbukatov could also start adding the information to the spec.

@mbukatov You'll need to send pull requests to @nthomas-redhat's branch from which he'll be making the pull request to this repository. He'll be able to merge your changes in his branch and they'll be reflected in the pull request in this repository.

**Comment by cybernth** [comment]
@mbukatov please add the changes to this spec

**Comment by mbukatov** [comment]
@brainfunked Like this https://github.com/nthomas-redhat/specifications/pull/1?

I don't have anything special to add, besides that I could add line that "name of Tendrl github group is not affected by this rename" - if I understand your statement right. And when I was trying to add this, I also fixed some syntax issues in the file.

**Comment by cybernth** [comment]
Issues linked with this are : 
https://github.com/Tendrl/tendrl-api/issues/38
https://github.com/Tendrl/tendrl_frontend/issues/62
https://github.com/Tendrl/node_agent/issues/101
https://github.com/Tendrl/ceph_integration/issues/58
https://github.com/Tendrl/gluster_integration/issues/88
https://github.com/Tendrl/common/issues/81

**Comment by brainfunked** [comment]
Addressed by https://github.com/Tendrl/specifications/pull/24
