### ISSUE TITLE
Tendrl objects should sync (from sds/node) independently at custom intervals

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/specifications#153]
Currently, Tendrl objects (node.network, node.cpu, sds objects like pool, volumes etc) sync at a global fixed interval

Required: Tendrl objects should sync at custom intervals per object based on their own sync intervals and priorities.

Why: This allows users to have more frequent updates/alerts to critical objects

**Comment by japplewhite** [comment]
The real intent here is to have Tendrl alert more quickly than 5 minutes for critical storage events like node down, failed disk, OSD down/out/missing, brick down, volume down/degraded. Other issues can sync on the regular update. I don't want to gold plate this though. If we could at least have a way to prioritize node and disk failures that would suffice.

**Comment by r0h4n** [comment]
OSDs, brick, volume: sync at at a 3 second interval to central store   cc: @anmolbabu whats the threshold alert update interval and are there intervals monitoring statuses of all of these objects 

Node and Disk inventory: Updated every 8 seconds. cc: @anmolbabu do you have alerts in place for failed disks, nodes ?
