### ISSUE TITLE
Threshold alerts for Tendrl objects

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/specifications#154]
Currently I am not sure if tendrl-alerting provides ability to get alerts on any object based on a custom threshold, This is required for users to be able to set custom thresholds on Tendrl objects and receive alerts for the same

@anmolbabu please provide inputs on this

**Comment by japplewhite** [comment]
@r0h4n Yes we need the ability to look at a config file for the various objects and alert based on that custom threshold. For example in some cases Ceph admins do not think that having 75% free space in their pool is enough and they want to make this lower. So there is a need for cluster thresholds and node thresholds that are configurable. I think the node thresholds should be a setting that applies cluster wide within a given set of cluster nodes by node type. For example all OSDs in a cluster. Having each and every node with it's own threshold is too much trouble and is overkill imo.
