### ISSUE TITLE
Enhance gluster cluster sync logic

### ISSUE THREAD

**Issue by shtripat** [Tendrl/specifications#167]
We need to enhance/modify the gluster cluster sync logic for
- Capture volume snapshot details and update in central store
- Instead of using `gstatus` aggregate the peer and volume status to decide the cluster's healthy status
- Instead of using `gstatus` aggregate the brick utilization for figuring out the volume utilization details
- Use `statvfs` for brick mounts to figure out the brick utilization - DONE
- Identify the arbiter volume type based on volme{n}.arbiter_count value
- Add rebalance estimation time under rebalance details
- No of geo-rep sessions and active geo-rep sessions
- Client connections per brick and aggregate for a volume (check if connections per brick available in get-state output)

**Comment by shtripat** [comment]
@Tendrl/tendrl-core plz review and add if something missed out here.

**Comment by nnDarshan** [comment]
@shtripat can you please add geo-rep

**Comment by shtripat** [comment]
@nnDarshan also I think the way volume options would be reported would undergo changes in get-state.
Also client connections details to be added.

**Comment by shtripat** [comment]
Closing this as all the required changes are merged including specifications PR as well.
