### ISSUE TITLE
Add required Ansible playbook configuration scripts for grafana

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/specifications#175]
Tendrl-ansible should support the following tasks to install and configure grafana.

1. Add the repo to install latest grafana and its dependencies
    install grafana, fontconfig, freetype*, urw-fonts

2. Configure grafana Server
    Configure and enable the Grafana server to start at boot time
    Add the required environment variables
    Set the log path, database, data source and the node details
 
3. Start the grafana-server service

**Comment by TimothyAsirJeyasing** [comment]
I hope we can add a separate spec for "Handle the un-manage cluster"

**Comment by brainfunked** [comment]
@TimothyAsirJeyasing yes, un-manage needs a separate spec.

**Comment by mbukatov** [comment]
I propose to close this issue, see https://github.com/Tendrl/specifications/pull/202#issuecomment-319308061 for reasoning. That said, we should have a separate spec for cluster unmanage.

**Comment by cybernth** [comment]
Ack. Closing this issue
