### ISSUE TITLE
Build package scripts for tendrl-monitoring-integration

### ISSUE THREAD

**Issue by TimothyAsirJeyasing** [Tendrl/specifications#178]
All the required scripts for building tendrl-grafana package should be added.
* Makefile, tendrl-grafana.spec, doc-help file and service file to be added.
* Its good to have selinux policies also for the tendrl-grafana metrics.

**Comment by cybernth** [comment]
Selinux is not in scope of this issue.  Also service file will be created when the corresponding changes are done in the code base(track as a different issue). Rest all are done and PRs are merged
