### ISSUE TITLE
Remove existing performance monitoring component and replace it with a new monitoring-integration component.

### ISSUE THREAD

**Issue by nnDarshan** [Tendrl/specifications#179]
The new monitoring-integration component would primarily focus on dynamic configuration of grafana, based on the topology changes in etcd. Some of these responsibilities would be:

- Keeping  track of the topology changes in etcd to configure the grafana dashboards to ensure that the correct nodes are part of the respective cluster dashboards.
- Configuring grafana authentication and authorisation (AA, covered in a separate spec), based on changes in the primary tendrl AA scheme.

**Comment by anivargi** [comment]
@nnDarshan please update the issue with the spec.

**Comment by mbukatov** [comment]
I see this item linked from https://github.com/Tendrl/specifications/milestone/3, so my question is: what should I review to evaluate configuration and installation impact on tendrl-ansible? I'm asking because this issue refers to work related to a previous milestone and I'm little confused why is this included in the next milestone as well.

**Comment by rishubhjain** [comment]
@mbukatov Monitoring-integration was introduced in the previous milestone. It is supposed to replace performance monitoring component. In every milestone there are some functionalities that are added to monitoring-integration. Some of the functionalities mentioned in issue description of this issue are implemented in 3rd milestone as well.

**Comment by mbukatov** [comment]
@rishubhjain ok, I understand that we improve tendrl-monitoring-integration in every milestone, but I'm unable to find out which changes/features are done in https://github.com/Tendrl/specifications/milestone/3 in particular. Shouldn't we have a different issue/specification for this? If we share single issue/specification in 3 different milestones, how do we agree on what is done in a particular milestone?

**Comment by mbukatov** [comment]
Ok, based on discussion with @r0h4n , I'm going to assume there is no additional impact on configuration/installation.

**Comment by rishubhjain** [comment]
For other features, a new issue is filed https://github.com/Tendrl/specifications/issues/247
