### ISSUE TITLE
Updated cluster list view

### ISSUE THREAD

**Issue by a2batic** [Tendrl/specifications#181]
- Remove the landing page with the create and import actions.
- Upon login, take the user straight to the cluster list view.
- Display imported and not imported clusters.
- Display any alerts related to the list clusters.
- Add a pop-up dialogue box, for each of the listed clusters, to show the cluster host list and any messages related to the specific cluster.
- Display basic utilisation or health information for imported clusters.

**Comment by cybernth** [comment]
Closing the issue as the related spec and PRs are merged
