### ISSUE TITLE
Initial UI refresh for the grafana integration

### ISSUE THREAD

**Issue by a2batic** [Tendrl/specifications#182]
Cluster specific objects like volumes and pools are to be removed from the main navigation bar. These views would only be available under a specific cluster. Update the navigation to allow quick switching between different clusters.

**Comment by brainfunked** [comment]
The following navigation entries would be available post the refresh from the [ui-legacy-code](https://github.com/Tendrl/ui/tree/ui-legacy-code) branch, which was created as part of the codebase refresh addressed in https://github.com/Tendrl/ui/issues/486.

* Remove the global navigation items for cluster specific objects such as volumes, pools, bricks etc.
* Retain the global navigation entries for Clusters, Hosts, Admin.
* Retain the global navigation entry for Alerts.
* Retain the top navigation entry for the notifications panel and authentication.

**Comment by brainfunked** [comment]
The following functionality would be carried forward from the [ui-legacy-code](https://github.com/Tendrl/ui/tree/ui-legacy-code) branch, which was created as part of the codebase refresh addressed in https://github.com/Tendrl/ui/issues/486.

* Notifications drawer
* Global alerts list
* Hosts list
* Tasks list
* Task details page
* Authentication

Other functionality such as workflows, list views and the various object details views would be ported subsequently. The updated cluster list views are being addressed in spec https://github.com/Tendrl/specifications/issues/181, while the import flow would be ported in spec https://github.com/Tendrl/specifications/issues/183.

**Comment by ltrilety** [comment]
I have several doubts about this issue. As the issue doesn't correspond to what was said in https://github.com/Tendrl/specifications/issues/200

Especially these two points makes me wonder:

- Remove the global navigation items for cluster specific objects such as volumes, pools, bricks etc.
- Retain the global navigation entries for Clusters, Hosts, Admin.
<br>
As I see it:

 - Via [Design A](https://redhat.invisionapp.com/share/2RCOE72PE) there should be `Clusters`, `Users`, `Mail Settings` and `SNMP Settings` navigation items plus upper menu with `notifications` no `Hosts` no `Admin` etc.
 - Via [Design B](https://redhat.invisionapp.com/share/8QCOEVEY9) there should be no just context selector and upper menu for users, snmp plus smtp settings, and alerts once again no `Hosts` etc.
 - Via mockups provided by @gnehapk there should be all navigation items including `volumes`, `bricks` etc.

So my question is what design is followed, if any?
Especially when I don't see any response on Ju comment https://github.com/Tendrl/specifications/issues/200#issuecomment-317777852 which is already two weeks old.

**Comment by a2batic** [comment]
@ltrilety, This setup is for Initial milestone, the specification and setup will be updated as soon as designs get finalized and we move towards other milestones.

**Comment by ltrilety** [comment]
@a2batic thanks for answer, it's just I don't understand what this particular changes improve in the long term point of view. If it should be the raw base from which a new UI will be created, I don't know why there is still `Hosts` list and `Tasks` list present. Anyway more logical to me seems to finish first the design or more precisely decide which one to follow. However it's your call.

**Comment by julienlim** [comment]
@ltrilety - we are recommending going with [Design B](https://redhat.invisionapp.com/share/8QCOEVEY9), and we're waiting on @sankarshanmukhopadhyay and Team to advise which [Milestone](https://github.com/Tendrl/specifications/milestones) it will land in.

**Comment by cybernth** [comment]
Closing this issue as the PRs associated with this issue are merged
