### ISSUE TITLE
Gluster metrics.

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/specifications#188]
Which gluster metrics are to be enabled.
How each of the metrics is going to be implemented.
How each of the metrics is to be visualised in grafana.
The alert thresholds (defaults) in grafana for each metric.
Query requirements on the grafana side to enable individual metrics or their aggregation.
Any flows to be added to the node agent for configuring any collectd plugins needed by the individual metrics.

**Comment by anivargi** [comment]
@anmolbabu  please associate the spec to the issue.

**Comment by anmolbabu** [comment]
https://github.com/Tendrl/specifications/issues/213#issuecomment-318001791
