### ISSUE TITLE
Alert notifications

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/specifications#190]
Rename the current alerting module(https://github.com/Tendrl/alerting) to Notifier.
Check if any changes are required to trim the module down to:
- Monitoring the alert conditions in etcd.
- Sending alert notifications to configurable receiving end-points: ui and smtp.

**Comment by mbukatov** [comment]
Which is the pull request with latest specification document I should review to see documentation (interested in configuration and setup) to understand changes needed in tendrl-ansible? I wasn't able to find the details I'm interested in.

I'm going to assume that all details I need to be aware of are described in: https://github.com/Tendrl/tendrl-ansible/issues/33
