### ISSUE TITLE
Tendrl ui alerts in grafana (stretch goal.)

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/specifications#194]
Copy tendrl generated dependent alerts to grafana for display.

**Comment by jjkabrown1** [comment]
Isn't this an advantage to embedding the Grafana dashboard vs. link and launch?  The Tendlr alert can remain on the upper part of the display, removing the need to transfer and add the complexity of sending tendlr alerts to grafana.

Thoughts?
