### ISSUE TITLE
Improve Import Cluster flow

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/specifications#213]
- Import cluster flow should use nodes with matching detected cluster id's for import and not rely on user input for the same.
- NS.tendrl.objects.Cluster needs new attr "errors" which point out cluster wide errors at present.
- NS.tendrl.objects.Cluster needs new attr "is_managed" which points out if the cluster is managed by tendrl or not.
- Per node errors related to the cluster will live at NS.tendrl.objects.DetectedCluster (which is per node)

**Comment by anmolbabu** [comment]
Gluster volume profile needs to be started for brick level iops to be available..
Which means import cluster should start profiling probably as a last step of the flow..

**Comment by julienlim** [comment]
@r0h4n @Tendrl/tendrl-core @Tendrl/qe @mcarrano 

Related UI design: 
See [Import Cluster mockup](https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/247445416) in [Design B](https://redhat.invisionapp.com/share/8QCOEVEY9).
