### ISSUE TITLE
Gluster Trusted Storage Pool details view

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/specifications#216]

**Comment by brainfunked** [comment]
Details for individual Gluster storage pools that include essential health information, list of all the volumes, hosts and bricks participating in the pool, mapping of volumes to bricks and bricks to hosts etc.

**Comment by brainfunked** [comment]
Point in time utlisation of hosts' CPU, memory and storage utlisation is not part of this spec. There are two corresponding issues at https://github.com/Tendrl/ui/issues/513 and https://github.com/Tendrl/node-agent/issues/585 where this is being tracked.
