### ISSUE TITLE
User management and access control

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/specifications#22]
Need a specification to tackle basic user/role management and access control. From the API perspective, it could be key based authentication where keys are allowed access to flows and state information based on the the following types:
* read-only
* safe
* unsafe

The read-only permission would apply for systems that want only to be able to monitor the storage systems via tendrl.

Safe and unsafe apply for operations and these need to be specified by the storage system flows.

**Comment by r0h4n** [comment]
@brainfunked @anivargi the read-only role to monitor the storage systems via tendrl can be done directly at the API layer itself by ensuring it doesnt create any jobs apart from Create and Import cluster in /queue
