### ISSUE TITLE
Monitoring-Integration as a daemon

### ISSUE THREAD

**Issue by rishubhjain** [Tendrl/specifications#233]
Monitoring Integration is required to be implemented as a service instead of present implementation

**Comment by brainfunked** [comment]
This spec currently tackles only the daemonisation of the monitoring-integration code. It also assumes a single instance of monitoring-integration to be responsible for all the clusters the tendrl instance manages. Long term, monitoring-integration would need to support one or more clusters per instance, and as such needs to be able to identify the clusters is is responsible for via the cluster context provided. This requires a separate spec.

**Comment by mbukatov** [comment]
Why there is no pull request?

**Comment by mbukatov** [comment]
Highlighting an important section for me:

> Install and run:
> 
> monitoring-integration will be installed in server node only. It will be
> installed and started by tendrl-ansible as a service. There is just one instance
> of monitoring-integration installed across all clusters.

@GowthamShanmugam Do you mean Tendrl Server or Storage Node? I would assume that Tendrl Server is right answer here (based on the fact that in previous milestone, we run `tendrl-monitoring-integration` script on Tendrl Server), but I would like to verify this.

**Comment by rishubhjain** [comment]
@mbukatov Yes Monitoring-integration will be installed on Tendrl Server, where grafana and graphite are also installed

**Comment by rishubhjain** [comment]
Completed
