### ISSUE TITLE
Logging implementation

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/specifications#28]
* Logs and alerts need to be treated as messages emitted by a component.
* A schema needs to be defined for emitted messages. This could be a json schema. The schema needs to include metadata that allows the exact point of origin of the message to be known.
* Message priorities, types etc. need to be defined at the time of emission.
* The integration/bridge applications must parse and restructure messages emitted by the storage system to fit in the tendrl message schema before emitting it.
* For messages that serve as notifications to the administrator (or alerts), exact error message must be hardcoded by the developers. No backtraces or system generated error messages should be sent as notifications to the administrator.
* Notifications sent to the administrator should provide sufficient context to enable debugging of the problem via investigation into the log files.
* Notifications and alerts need to be delivered to the node agent alert sockets (specification pending)
* Commons needs to implement a logging library that hides all the implementation details and configuration options from any of the components using the library. Components should be able to blindly emit messages to the common logging module and it should be able to deliver them to either syslog, log files, alert sockets etc. depending upon the metadata and configuration. (https://github.com/Tendrl/common/issues/62, https://github.com/Tendrl/common/issues/60)
* Syslog must be the default logging configuration. Logging to individual configuration files should be thoroughly discouraged.

**Comment by GowthamShanmugam** [comment]
#94

**Comment by julienlim** [comment]
@brainfunked Here's the link to where the common logging namespace docs are: https://github.com/ViaQ/elasticsearch-templates/tree/master/namespaces.

**Comment by r0h4n** [comment]
Please take inspiration from existing Job/queuing frameworks (Gearman, Celery, OpenStack, Kubernetes) to figure out the schema/metadata that would be needed with all messages (logs and alerts)

Alerts/Logging schemas:
- https://wiki.openstack.org/wiki/NotificationEventExamples  (Alerts, Notifications) /cc @anmolbabu 
- http://docs.openstack.org/developer/nova/notifications.html

**Comment by brainfunked** [comment]
Copying from https://github.com/Tendrl/specifications/issues/55, which has been closed as a duplicate of this issue:

Each operation should be created as directory, with the id of the operation as the key. Keys must be created [in order inside this directory](https://github.com/coreos/etcd/blob/master/Documentation/v2/api.md#atomically-creating-in-order-keys). The first key inside the directory must always be a dump of the job parameters and the contexts (tendrl, node). Subsequent updates to the operation must be posted as individual keys created in the directory. Each such object must be a properly tagged message, based on https://github.com/Tendrl/specifications/pull/94. Any node agent specific decisions (such as a job being picked up, distributed etc.) must also be stored as objects in the operation directory, as an update (these need not be displayed as a notification to the administrator).

The tagged messages would contain the appropriate metadata to enable the API to filter out only the notifications to be sent as job updates. The API would need to accept the key from which all subsequent updates must be returned. The absence of the key would indicate that all the updates regarding the operation must be returned. This feature is useful to deliver only the new messages to the client (UI, CLI etc.), for a tracked operation.
