### ISSUE TITLE
Node agent tagging and tag based job routing

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/specifications#44]
It should be possible to assign tags to individual node agents. Flows could have tags statically indicates so that once jobs are created from these flows, the tags can be included in the jobs' metadata. Node agents with the matching tag should prioritise on picking up these jobs.

In the future this functionality will allow priority based job routing or role based job routing. For instance, if a node agent has been tagged as the provisioning controller, it will pick up the jobs tagged as provisioning. This is intended to be a framework feature to allow any kind of mapping, however the mapping itself would be introduced in a static manner in the code by the developers, depending upon the evolution of the functionality of the node agents.

This would impact the following:
* The node_context object would contain a list of tags,
* The definition schema would be updated to allow flows to contain preferred tags,
* The API, validation etc. need to accommodate the tags being present in the flows and being added as metadata to the jobs.

**Comment by nnDarshan** [comment]
**NODE AGENT TAGGING:**
As first phase of implementation on node agent tagging, I have considered tags needed for basic import cluster. they are as follows:
* TENDRL - All nodes where tendrl-node-agent service is running will be tagged as TENDRL node
* TENDRL_SERVER - Node where tendrl-api and etcd service are running will be tagged with this tag.
* TENDRL_GLUSTER - Nodes where tendrl-gluster-integration service is running will be tagged with this tag.
* TENDRL_CEPH - Nodes where tendrl-ceph-integration service is running will be tagged with this tag.
* GLUSTER - Nodes where glusterd service is running
* CEPH - Nodes where ceph-osd or ceph-mon service is running
* CEPH_OSD - Nodes where ceph-osd service is running
* CEPH_MON - Nodes where ceph-mon service is running 

NOTE: Tags related to monitoring and provisioning will be added later

**Comment by nnDarshan** [comment]
@brainfunked @shtripat @nthomas-redhat @r0h4n @anmolbabu Please provide your thoughts regarding above comment

**Comment by shtripat** [comment]
@nnDarshan The only point I have is related to TENDRL_GLUSTER and GLUSTER or TENDRL_CEPH ad CEPH. How one is different from other? All the gluster nodes should have gluster-integration bits running.

**Comment by nnDarshan** [comment]
@shtripat I feel this distinction is needed because, untill cluster is imported, gluster integration service wont be running. So a flow like ImportGlusterCluster can be targetted at GLUSTER nodes. But a flow like GlusterVolumeCreate should be targeted at TENDRL_GLUSTER node.

**Comment by shtripat** [comment]
Then its fine. List looks good at the moment to me.

**Comment by cybernth** [comment]
> NODE AGENT TAGGING:
> As first phase of implementation on node agent tagging, I have considered tags needed for basic import cluster. they are as follows:
> 
> TENDRL - All nodes where tendrl-node-agent service is running will be tagged as TENDRL node
> TENDRL_SERVER - Node where tendrl-api and etcd service are running will be tagged with this tag.
> TENDRL_GLUSTER - Nodes where tendrl-gluster-integration service is running will be tagged with this tag.
> TENDRL_CEPH - Nodes where tendrl-ceph-integration service is running will be tagged with this tag.
> GLUSTER - Nodes where glusterd service is running
> CEPH - Nodes where ceph-osd or ceph-mon service is running
> CEPH_OSD - Nodes where ceph-osd service is running
> CEPH_MON - Nodes where ceph-mon service is running
> NOTE: Tags related to monitoring and provisioning will be added later

Couple more I could think of:
* Node where ceph-installer/gdeploy is running
* Node where calamari-lite is running

**Comment by r0h4n** [comment]
@brainfunked we have finished tag based routing.

Although priority routing is something of a needinfo on you, please comment, I remember us discussing topic queues for tags or something on those lines
