### ISSUE TITLE
Service detection modules for the node agents

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/specifications#46]
Node agents need to ship with modules that can detect various services already present on the nodes. This includes, but is not limited to:
* ceph services
* gluster services
* tendrl api
* tendrl monitoring application
* tendrl central store

The inventory populated by the node agent in the central store should include information about all the detected services. The list could then be presented to the administrator via the API and the UI to allow selection of the nodes for an import operation.

This feature facilitates future features for monitoring, managing, provisioning and upgrading tendrl's own components. Furthermore, this also lends to better support for co-location of tendrl with the storage systems.

**Comment by cybernth** [comment]
@brainfunked , are we planning to run node-agents on the server where we run Tendrl central store and tendrl monitoring application ?

**Comment by brainfunked** [comment]
@nthomas-redhat Yes. There's no reason the node agent cannot already do this. This allows us to resuse the node agent's monitoring and provisioning functionality for tendrl components and in the future would allow tendrl components to be co-located on the storage nodes.

**Comment by nnDarshan** [comment]
Implementation here https://github.com/Tendrl/commons/pull/101
