### ISSUE TITLE
Internal provisioning wrapper for ceph

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/specifications#48]

**Comment by cybernth** [comment]
https://github.com/Tendrl/ceph-integration/issues/106

**Comment by cybernth** [comment]
https://github.com/Tendrl/specifications/pull/132

**Comment by cybernth** [comment]
https://github.com/Tendrl/node-agent/issues/202

**Comment by brainfunked** [comment]
API documentation in https://github.com/Tendrl/specifications/pull/139.

**Comment by brainfunked** [comment]
Updated job structure and validations in https://github.com/Tendrl/specifications/pull/146.
