### ISSUE TITLE
Internal provisioning wrapper for gluster

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/specifications#49]

**Comment by brainfunked** [comment]
Tagging @sac

**Comment by brainfunked** [comment]
@nnDarshan Please investigate what happens in scenarios where the disk already has partitions. Do we clear the disk or simply ignore it altogether?

**Comment by mkudlej** [comment]
@brainfunked @nnDarshan It will be great to do it like ceph-disk does. Ceph-disk can detect partitions and skip that device to another one, if user uses autodetect feature in ceph-ansible.

**Comment by nnDarshan** [comment]
@brainfunked Gdeploy wont create bricks out of partitioned disks. So, tendrl has to make sure that it provides a list of free disks to gdeploy for brick creation(anyhow we already maintain a list of used and free disks)

Also I feel its not safe to touch partitioned disks as user might be using it for some purpose, and we cleaning it might lead to data loss. So its better to consider only free disks.

**Comment by nnDarshan** [comment]
@mkudlej gdeploy doesn't have automatic disk detection feature and user should specify the list of disks to be used for creating bricks. If at all user provides a partitioned disk it doesn't create brick from it.

So I feel tendrl has the responsibility of providing a list of free disks to gdeploy

**Comment by nnDarshan** [comment]
@brainfunked do you have any plans about how and when to deploy gdeploy and the environment needed for it ? as you might be aware gdeploy needs passwordless ssh to be set up between gdeploy node and all other gluster nodes as a prerequisite.

**Comment by r0h4n** [comment]
@nnDarshan We will be having password less public key ssh between all tendrl nodes

**Comment by nnDarshan** [comment]
@r0h4n Thanks for confirming that. As far as this issue is concerned I will assume that password less is already available. We can tackle how we achieve that separately
