### ISSUE TITLE
Import cluster workflow

### ISSUE THREAD

**Issue by cybernth** [Tendrl/specifications#54]
Currently to import a cluster, user expected to provide the all the nodes in the cluster as input. This will be inconvenient if the size of the cluster is large. Instead the usecase flow is expected to be modified as:
- select one of the node in cluster
- use the selected node to get the details of the cluster
- submit the request to all the nodes to import the cluster

**Comment by brainfunked** [comment]
@nthomas-redhat I think it would be a good idea to detail out the import cluster workflow as a whole and incorporate these changes in the same specification.

**Comment by brainfunked** [comment]
Linked to https://github.com/Tendrl/specifications/issues/56

**Comment by brainfunked** [comment]
Depends on https://github.com/Tendrl/specifications/issues/46

**Comment by cybernth** [comment]
@Tendrl/tendrl-core , @Tendrl/qe please review

**Comment by cybernth** [comment]
@anivargi @brainfunked @r0h4n please review

**Comment by brainfunked** [comment]
Can leverage https://github.com/Tendrl/specifications/issues/55

**Comment by brainfunked** [comment]
Based on the updates (https://github.com/Tendrl/specifications/pull/100) now sent to the node agent namespaces specification (https://github.com/Tendrl/specifications/issues/87), the import cluster functionality would play out as follows:

Prerequisite:

* Node agents are installed on each of the nodes to be imported and can connect to etcd (auto-deployment of the node agents themselves is a provisioning task and will be tackled with the other provisioning workflows, in a separate specification).


Upon starting up, the node agent performs the following:

* Run the platform detection modules, stop at the first positive identification, gather the data and push it to etcd.
* Run the hardware and network inventory functionality and push the inventory to etcd.
* Run all the detection modules, gather all the data, create the `detected_cluster` object and populate etcd.
* Set the node in the correct state. For nodes where a storage system has been detected, the state would be `Import Pending`. For other 'clean' nodes, the state would be `Managed`.

This is how the import cluster workflow will be triggered from the API:

* A generic, hardcoded `ImportCluster` flow is defined globally in the master definition file. This flow requires the following parameters:
  - cluster_id
  - cluster_type
  - cluster_detection_id
  - cluster_name
  - cluster_nodes
  - Optionally, cluster_version
* `cluster_id` is generated by the API. At the time of the job creation, the appropriate cluster id based namespace is created under `/clusters`.
* `cluster_name` is a name the administrator provides to identify the cluster with, in the future. The other parameters are used just for verification that the detected cluster is indeed the one to be imported.
* The import cluster job would contain a list of all the nodes which could participate in the job. This is being addressed in https://github.com/Tendrl/specifications/issues/102.
* One of the node agents in the list of nodes locks and picks the job up.
* The node agent creates jobs for individual node agents to run specific detection modules again.
* Individual node agents put their nodes in the `Importing` state.
* The individual jobs invoke the role specific detection modules again, to verify that the cluster map hasn't changed after the import operation has been initiated.
* If one of the jobs fails, the import cluster job fails and the appropriate error is returned as the job's output, indicating the detected change. Node state is reset to `Import Pending`.
* If the detection jobs all pass, the node agent invokes the storage system namespace specific import cluster flow (`ImportGlusterCluster` or `ImportCephCluster`).
* This storage system specific import cluster flow invokes specific jobs for specific nodes participating in the `ImportCluster` flow, based on their roles in the cluster. Only the nodes with the appropriate job would have such a job invoked against themselves.
* These individual node agents put their nodes in the `Importing` state, if they aren't already.
* The individual jobs invoke the flows to install, configure and start the integration modules on specific nodes.
* The startup of the integration modules should be a blocking call. Upon successful connection to etcd and connection to the cluster, the integration module should return success.
* The integration modules start populating the cluster data under `/clusters/<cluster_id>`.
* Once the data has been populated, the modules communicate the end of their import operation to their respective node agents[1], which create the `cluster_id`, `cluster_role` and `cluster_attributes` objects under each of the nodes.
* The node agent which locked the original `ImportCluster` job creates new jobs to ensure that all the nodes involved in the original flow are in the `Imported` state.
* The node agent marks the original `ImportCluster` job as successfully finished.

[1] This looks like a new specification to enable node local communication between the node agent and it's managed integration. An admin socket could be created via which the node agent and the integration module could communicate. The node agent would be able to invoke specific commands against the integration module and the module in turn could provide updates to this command on the same socket back to the node agent.

**Comment by shtripat** [comment]
@brainfunked the above flow I would like to have been depicted in a state diagram or at least a flow chart. It would be more clear.

**Comment by nnDarshan** [comment]
@brainfunked what happens if the detection modules on all the nodes succeeds but the sub job for namespace specific import cluster fails on some of the nodes ? wouldn't this lead to an inconsistent state where some of the nodes start reporting cluster state to etcd, but the import cluster flow has failed as sub job on some of the nodes failed ?

**Comment by cybernth** [comment]
@nnDarshan the failed jobs will be reattemped until they get succeeded.
@brainfunked suppose if the job didn't get succeed after a number of retrires, what is the plan of action? rollback or report a 'Partial failure'?
Also  what about the APIs? I assume that we are on agreement that we will have two APIs involved in import cluster flow - one for getting the cluster nodes(can leverage the data poplated by detection modules) and another one for importing the cluster
