### ISSUE TITLE
Updates for in flight operations

### ISSUE THREAD

**Issue by cybernth** [Tendrl/specifications#55]
Updates include details for every atom executed, including timestamps, actual invocation (cli, api etc.), output etc.

**Comment by r0h4n** [comment]
Is there a spec for this yet?

**Comment by cybernth** [comment]
@r0h4n , not yet

**Comment by brainfunked** [comment]
@nthomas-redhat Do refer to the review comment https://github.com/Tendrl/specifications/pull/94#pullrequestreview-14123541 on the logging specification as that should provide some inputs that could be used to construct this specification.

**Comment by brainfunked** [comment]
Each operation should be created as directory, with the id of the operation as the key. Keys must be created [in order inside this directory](https://github.com/coreos/etcd/blob/master/Documentation/v2/api.md#atomically-creating-in-order-keys). The first key inside the directory must always be a dump of the job parameters and the contexts (tendrl, node). Subsequent updates to the operation must be posted as individual keys created in the directory. Each such object must be a properly tagged message, based on https://github.com/Tendrl/specifications/pull/94. Any node agent specific decisions (such as a job being picked up, distributed etc.) must also be stored as objects in the operation directory, as an update (these need not be displayed as a notification to the administrator).

The tagged messages would contain the appropriate metadata to enable the API to filter out only the notifications to be sent as job updates. The API would need to accept the key from which all subsequent updates must be returned. The absence of the key would indicate that all the updates regarding the operation must be returned. This feature is useful to deliver only the new messages to the client (UI, CLI etc.), for a tracked operation.

**Comment by brainfunked** [comment]
This specification will be impacted by the comments on the logging specification pull request at https://github.com/Tendrl/specifications/pull/94#pullrequestreview-17399508. @GowthamShanmugam please update this spec accordingly.

**Comment by brainfunked** [comment]
Given that the logging implementation specification, https://github.com/Tendrl/specifications/issues/28, is a superset of this specification and the pull request for it addresses all the requirements in this specification, https://github.com/Tendrl/specifications/pull/94, I'm copying the details from this specification over there and closing this one.
