### ISSUE TITLE
Import cluster UI

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/specifications#56]
We are going with dynamic generation and we have common form generator.
we are using this form generator for generate the form but in the import cluster case , we have different ux design , not common select box or textbox as we have in form generator.
so finally for import cluster we are not going ahead with dynamic generation for now. it will be static but we will use directive for table view.

**Comment by brainfunked** [comment]
I'm renaming this specification to address it's scope properly. This needs to be linked to the import cluster related jira issues and the specification needs to address how you're planning on implementing the UI itself and at each step, link to the appropriate UX slide.

**Comment by brainfunked** [comment]
Linked to https://github.com/Tendrl/specifications/issues/54

**Comment by kamleshverma1** [comment]
Import cluster UX slide : 
https://docs.google.com/presentation/d/18jbUSbQbbcDBo4PI58q-uZbKTm0Ai0msePpsMfLio-k/edit#slide=id.g154cd53edc_0_0

**Comment by mcarrano** [comment]
@kamleshverma1 Note that the UX link you pasted above is to an old design.  The latest/current design is posted to InVision here: https://redhat.invisionapp.com/share/R88EUSGJK

**Comment by kamleshverma1** [comment]
Linked for Jira Tickets  : https://tendrl.atlassian.net/browse/TEN-171

**Comment by kamleshverma1** [comment]
Linked for tendrl-frontend issue : https://github.com/Tendrl/tendrl_frontend/issues/63

**Comment by julienlim** [comment]
I believe the Import Cluster JIRA user stories that this spec needs to link to are as follow:
* Import Ceph 2.x cluster (https://tendrl.atlassian.net/browse/TEN-4)
* Import Gluster 3.2 cluster (https://tendrl.atlassian.net/browse/TEN-3)
