### ISSUE TITLE
Donut and Sparkline Chart Component

### ISSUE THREAD

**Issue by kamleshverma1** [Tendrl/specifications#84]
Generally , We should have one common component for draw the charts (donut or sparkline chart) as shown in UX design. ( https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/185937524 )

**Comment by kamleshverma1** [comment]
Linked https://github.com/Tendrl/tendrl_frontend/issues/67

**Comment by brainfunked** [comment]
@kamleshverma1 the details in the comments, can you send them as a pull request so we can merge it?

**Comment by kamleshverma1** [comment]
@brainfunked doing same ( writing spec for the same)
