### ISSUE TITLE
Filtering out duplicate Gluster events

### ISSUE THREAD

**Issue by atinmu** [Tendrl/specifications#86]
With Gluster eventing integration there is possibilities that tendrl will keep on receiving duplicate events (especially like the disconnect ones) till a successful reconnect happens. It'd be good to have some infrastructure in tendrl to have in place where these events can be shown to the users/monitoring console once instead of repetition.

**Comment by brainfunked** [comment]
Also, https://bugzilla.redhat.com/show_bug.cgi?id=1405352 is an upstream gluster issue in the same domain. However, we're currently not tracking georep and hence wouldn't affect us.

@atinmu do you have a list of duplicate events which we should filter?

**Comment by atinmu** [comment]
@brainfunked  I'll provide you the list in sometime. If I don't sent me a reminder too (in a week's time) ;)

**Comment by brainfunked** [comment]
@atinmu will tag you for an action item in the daily check in, that way, we'll have daily reminders :) Assigning this issue to you currently, as github has no equivalent to NEEDINFO.

**Comment by atinmu** [comment]
Here are the additional list of gluster events where tendrl needs to apply a filter to avoid duplicate ones:

1. PEER_DISCONNECT
2. GEOREP_PASSIVE
3. CLIENT_CONNECT
4. CLIENT_DISCONNECT
