### ISSUE TITLE
Namespaces and flows to be carried with the node agent by default

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/specifications#87]
Tendrl API discovers and advertises any possible functionality via the namespaced flows in the definition files. This approach allows for addition flows to be implemented and made available dynamically via the API.

Node agent serves as the component responsible for implementing the flows and namespaces that provide the core tendrl functionality. The core tendrl functionality such as service detection, hardware inventory etc. is served via hardcoded flows and code shipped with the node agent. Wherever applicable, the core functionality is enabled via commons, as a framework feature.

Building on the core framework, support for specific storage system features of pluggable stacks can be enabled, without impacting the core framework itself. However, in some cases, it is impossible to achieve a complete separation between the supported storage systems and Tendrl. For example, to enable support to detect (https://github.com/Tendrl/specifications/issues/46), import (https://github.com/Tendrl/specifications/issues/54) and provision Ceph (https://github.com/Tendrl/specifications/issues/48) and Gluster (https://github.com/Tendrl/specifications/issues/49), the node agent itself needs to ship with at least the essential glue that could pull in the necessary integration components dynamically (https://github.com/Tendrl/specifications/issues/47, https://github.com/Tendrl/specifications/issues/51, https://github.com/Tendrl/specifications/issues/52).

This specification has been created to clearly separate out the various integrations by shipping only the bare necessary namespaces and flows that would ship with the node agent itself to allow the addition components to be then pulled in dynamically and in the future allow the support for different versions of the storage systems or even new storage systems to be added dynamically to a Tendrl deployment without requiring any changes in the code.

A part of this specification had originally been intended to be documented in the specification to define the scope of the integration modules, https://github.com/Tendrl/specifications/issues/52. Once this specification has been accepted, the details will be populated in that issue accordingly.

In addition to storage system support, the pluggable tendrl stacks such as monitoring, need to be allowed to be dynamically plugged into an existing Tendrl deployment. The tendrl namespace needs to allow support for such additional definition file updates to be deployed. This specification would also address this problem. It should enable the provisioning of the monitoring stack, https://github.com/Tendrl/specifications/issues/42, to progress.

**Comment by r0h4n** [comment]
Apart from provisioning the mon and alerting stack via the node-agent, we have implemented the rest
